const mongoose = require('mongoose')

const productSchema = new mongoose.Schema({
    title:
    {
        type:String
    },
    description:
    {
        type:String
    },
    price:
    {
        type:Number
    },
    discountedPrice:
    {
        type:Number
    }
    ,
    discountedPercent:
    {
        type:Number
    },
    quantity:
    {
        type:Number
    },
    brand:
    {
        type:String,
    }
    ,color:
    {
        type:String
    },
    sizes:[{
        name:{type:String},
        quantity:{type:String}
    }],
    imageUrl:
    {
        type:String
    },
    ratings:
    [{
        type:mongoose.Schema.Types.ObjectId,
        ref:'rating'
    }],
    reviews:[{
        type:mongoose.Schema.Types.ObjectId,
        ref:'reviews'
    }],
    numRatings:
    {
        type:Number,
        default:0
    },
    category:
    {
        type:mongoose.Schema.Types.ObjectId,
        ref:'categories',
    },
    createdAt:
    {
        type:Date,
        default:Date.now
    }
})
const Product = mongoose.model('product',productSchema)
module.exports = Product;